### PR TITLE
Blake2b 256 function signature hashing mechanism

### LINKED ISSUE #66: Change the function signature Hashing mechanism
According to the discussion [here](https://github.com/paritytech/ink/issues/776) We have actually been determining(computing) the function signature for ink! wrongly, the function signature should actually be a `BLAKE2b-256` hashing of the ink! contract function name as opposed to what we currently implemented which is similar to Solidity.

For example, to determine the function signature for setting handler in ink!, it should be determined as such:
`BLAKE2b-256(u8`) as opposed to `Keccak256(u8)`

Therefore,  `Treasury::set_handler` hashed with`BLAKE2b-256` is the right way of determining a function signature in ink! as opposed to` set_handler([u8;32],[u8;4])` hashed with `Keccak256.`

### PR DESCRIPTION
**Pull request by dharjeezy**
closes #66

### CODE REVIEW

File: contracts/anchor_handler/lib.rs [hunk 1]
```diff
@@ -207,10 +209,9 @@ mod anchor_handler {
             arguments: &[u8],
         ) -> Result<()> {
             if function_signature
-                == Keccak256::hash_with_four_bytes_output(
-                    b"set_handler([u8;32],[u8;8])".to_vec().as_slice(),
+                == blake2b_256_4_bytes_output(
+                    b"VAnchor::set_handler([u8;32],[u8;8])".to_vec().as_slice(),
```
Comment (drewstone) [inline contracts/anchor_handler/lib.rs:213]: It is just the hash of the function name not the function signature.

**Review by drewstone — CHANGES_REQUESTED** [review]
Please fix so that it matches the expected selectors. If something is unclear please ask.

File: contracts/anchor_handler/lib.rs (hunk 1 above)
Comment (dharjeezy) [reply contracts/anchor_handler/lib.rs]: Oh...I missed this. The rest are not like that.
I have fixed the anomaly now
